### ISSUE TITLE
IPN validation failing due to http / https inconsistency

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-magento#10]
On my server this line:
https://github.com/YellowPay/yellow-magento/blob/master/app/code/local/Yellow/Bitcoin/controllers/IndexController.php#L70
Is returning an https:// URL
but the callback registered with Yellow is http:// so the validation is failing.

These are my URL settings:
![image](https://cloud.githubusercontent.com/assets/3465100/6585385/c8ca9eec-c72e-11e4-8d31-f17386637840.png)

And I was accessing the magento store through http:// (not https://)

**Comment by JamesPiechota** [comment]
I've also confirmed that the Yellow server was posting the IPN to an http:// URL - so not sure why the magento getCurrentUrl call is returning https://

**Comment by tawfekov** [comment]
this issue is kind of wrong configuration that can't be used in real life , cuz magento will always create a redirect to secured url causing the IPN to fail 

it won't fix

**Comment by JamesPiechota** [comment]
Specifically these are the test cases @tawfekov confirmed:

```
TEST CASE : both urls are http : use frontend is NO -> IPN signature validation succeeded PASS
TEST CASE : both urls are http : use frontend is YES -> IPN signature validation succeeded PASS
TEST CASE : both urls are https : use frontend is YES -> IPN signature validation succeeded PASS
TEST CASE : both urls are https : use frontend is NO -> IPN signature validation succeeded PASS
TEST CASE : insecure url is http, secure url is https : use frontend is NO -> IPN signature validation FAILED as expected | there was a redirect 
```

The failing case is an edge case (and really represents a store configuration error), so it's unlikely to be hit in the real world and is tough to fix.
