### ISSUE TITLE
Error message on overpayment with fullscreen widget

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-magento#13]
If you request a refund when using the fullscreen widget you're redirected to a page with this message:
![image](https://cloud.githubusercontent.com/assets/3465100/6699890/82bfaa06-ccc3-11e4-9e37-f6982be9ce8f.png)

Could you update the message to instead say (first line above the divider, the rest below)

Thank you for submitting your refund request!
We'll get in touch very soon. In the meantime, if you have any questions, you can reach us at support@yellowpay.co

Order # 100000017
Click here to continue shopping.

**Comment by tawfekov** [comment]
all messages will be showing on frontend / customer pages  as you may see in the attached image 
![order 145000039](https://cloud.githubusercontent.com/assets/94997/6992963/75cceab0-daed-11e4-84a3-785df6d43c43.png)
