### ISSUE TITLE
Add PHP SDK wrapper for the API

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-magento#16]
SDK should abstract at least:
- Creating an invoice, including building the HMAC authentication headers
- Validating the authentication of an IPN

I've created this public repo (and add @tawfekov as a writer) here:
https://github.com/YellowPay/yellow-sdk-php

Here are two examples (python and node):
https://github.com/YellowPay/yellow-sdk-python2
https://github.com/YellowPay/yellow-sdk-node

**Comment by tawfekov** [comment]
built in https://github.com/YellowPay/yellow-sdk-php
