### ISSUE TITLE
Option to have text for Payment Method instead of image

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-magento#20]
The default should still be to show the "Bitcoin | Powered by Yellow" image, but we should include an option in the admin panel to change it to simple text: "pay with Bitcoin (what is bitcoin?)" where the "what is bitcoin?" is still a link.

**Comment by JamesPiechota** [comment]
Let's make text the default - the image can be too jarring on too many pages.

**Comment by tawfekov** [comment]
this was fixed on commits aa396991 , 9842882c
