### ISSUE TITLE
Add some padding below the payment widget in the full page invoice

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-magento#26]
add `padding-bottom: 13px` to `.yp-widget-container`

![image](https://cloud.githubusercontent.com/assets/3465100/8130654/2a37c86a-10c9-11e5-8d2b-c2dfd1cab62a.png)

**Comment by tawfekov** [comment]
I've added it on d2a8ac2c7 and didn't have any update , I think we had to do it on the server 
@JamesPiechota can you please confirm ?
