### ISSUE TITLE
Unexpected Alert dialogs in full page invoice

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-magento#8]
It looks like there are other domains (e.g. facebook) that sometimes send messages to the parent window. Those messages, since they don't come from Yellow, are treated as errors and an alert dialog is shown. Either figure out how to have the parent screen only listen to messages from the widget, or, worst case, take away the alert dialog so we just silently skip unexpected messages.

**Comment by JamesPiechota** [comment]
FYI @DaveAchkar @tawfekov

**Comment by tawfekov** [comment]
I'd vote for silently skip unexpected messages , I don't think it may hurt the process

**Comment by JamesPiechota** [comment]
I agree. I'll do that anyways - I'll just do a quick look to see if we can restrict the messages we listen to.

**Comment by JamesPiechota** [comment]
@tawfekov I just realized the code to handle this is in the plugin. Can you make the change? Assigning to you.

i.e. exactly as you suggested, silently skip the unexpected messages

Change:

```
if (event.origin != "https://yolanda-perkins.herokuapp.com" && /\.yellowpay\.co$/.test(event.origin) == false ) {
    alert("Received message from unexpected domain: " + event.origin);
    return;
}
```

To:

```
if (event.origin != "https://yolanda-perkins.herokuapp.com" && /\.yellowpay\.co$/.test(event.origin) == false ) {
    return;
}
```

**Comment by tawfekov** [comment]
updated & pushed to git
